spring.application.name=bff
server.port=8080
downstream.user-service.url=http://localhost:8081
downstream.auth-service.url=http://localhost:8082
downstream.message-service.url=http://localhost:8083

jwt.secret=change-me-in-prod-please-32bytes-minimum-secret